name: Push Docker Image To Azure Container
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create json file
        uses: actions/checkout@v3
      - shell: bash
        run : |
          echo "${CREDENTIALS}" >> credentials.json
          sudo apt-get install -y zip
          zip -r fastnext.zip .
          password=Tthiane@94
          sshpass -p "$password" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 22400 fastnext.zip root@155.133.26.100:/root
