name: connect to remote ssh command
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pages
    steps:
      - uses: actions/checkout@v3
      - name: "Use response"
        shell: bash
        run: ls -l
