name: Push Docker Image To Azure Container
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Contaiern Registry
        uses: docker/login-action@v2
        with:
          registry: fastnextimage.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fastnextimage.azurecr.io/fastnextimage:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy And Update AKS
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az aks get-credentials --resource-group devtuto --name fastnextcluster
            kubectl rollout restart deploy
