name: connect to remote ssh command
on:
  push:
    branches: [ "mains" ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            sudo apt update && sudo apt -y upgrade
            sudo apt install nginx -y
            sudo systemctl enable nginx
            sudo systemctl start nginx



